### ISSUE TITLE
ProfileNavigation

### ISSUE THREAD

**Issue by adamryvola** [adamryvola/shared-components#14]
https://edookit-schools-dev.herokuapp.com/schools/3

![11 - profilenav](https://cloud.githubusercontent.com/assets/6860415/19434195/68507a28-9464-11e6-830d-760a4707c301.png)

**Comment by dltmd6262** [comment]
Added component to library, still need to find where it's being used.

**Comment by adamryvola** [comment]
menu-item should be relative-link (#discussion), no onItemSelected callback right now, just "to" attribute

**Comment by adamryvola** [comment]
https://edookit-schools-dev.herokuapp.com/schools/3
In school-picker this component is integrated, but doesn't work - no link, no hightlight on scroll

**Comment by zenway-js** [comment]
The problem is in installation of shared-components...
I removed my ./node_modules/ and installed it again.
And I can see only old code in ProfileNavigation.js
http://screenshots.client-demo-site.net/scn-20161105-182840-49zvk.png

But in repository I can see new code https://github.com/adamryvola/shared-components/blob/master/dist/ProfileNavigation/index.js

http://screenshots.client-demo-site.net/scn-20161105-182943-zwlvy.png

I think it can be stored somewhere locally...

**Comment by MogilevichDmitry** [comment]
Replace profile-nav on school-picker and on sharing-portal

**Comment by adamryvola** [comment]
Solved
